backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'events'
    label: 'Events'
    folder: 'src/pages/events'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'events-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Lead text', name: 'leadText', widget: 'text' }
      - { label: 'Review', name: 'review', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'text' }
      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        fields:
          - { label: 'Gallery Image', name: 'galleryimage', widget: 'image' }

  - name: 'retreats'
    label: 'Retreats'
    folder: 'src/pages/retreats'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'retreats-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Location', name: 'location', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'text' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Review', name: 'review', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'text' }
      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        fields:
          - { label: 'Gallery Image', name: 'galleryimage', widget: 'image' }

  - name: 'home'
    label: 'Home'
    folder: 'src/pages/home'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'home-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Slider'
        name: 'slider'
        widget: 'list'
        fields:
          - { label: 'Slider Image', name: 'sliderimage', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Cards'
        name: 'cards'
        widget: 'list'
        fields:
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }

  - name: 'events-page'
    label: 'Events Page'
    folder: 'src/pages/events-page'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'events-page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Lead text', name: 'leadText', widget: 'text' }
      - { label: 'Review', name: 'review', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'text' }

  - name: 'retreats-page'
    label: 'Retreats Page'
    folder: 'src/pages/retreats-page'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'retreats-page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Lead text', name: 'leadText', widget: 'text' }

  - name: 'home'
    label: 'Home'
    folder: 'src/pages/home'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'home-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Slider'
        name: 'slider'
        widget: 'list'
        fields:
          - { label: 'Slider Image', name: 'sliderimage', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Image', name: 'image', widget: 'image' }
